// файл UIAction.h

#ifndef UI_ACTION_H
#define UI_ACTION_H

enum UIAction {
    ACT_MOVE_ACTIVE_ITEM_PREV,
    ACT_MOVE_ACTIVE_ITEM_NEXT,
    ACT_MOVE_PARAM_PREV,
    ACT_MOVE_PARAM_NEXT,
    ACT_EDIT_PARAM_INCREASE,
    ACT_EDIT_PARAM_DECREASE,
    ACT_SAVE,
    ACT_BACK
};

#endif